// <auto-generated />
namespace OnlineJwellery.DataContexts.OnlineJewelleryMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RenamingForeignKeypart2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenamingForeignKeypart2));
        
        string IMigrationMetadata.Id
        {
            get { return "201805201258129_RenamingForeignKeypart2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
